import Head from 'next/head'
import React from 'react'
import Footer from './Footer'
import Navbar from './Navbar'
//import Navbar from './Navbar'

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <meta charset='UTF-8' />
                <meta name="description" content="Generated by create next app" />
                <meta http-equiv='X-UA-Compatible' content='IE=edge' />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>Create Next App</title>
            </Head>
            <header>
                <Navbar />
            </header>
            <main>
                {children}
            </main>
            <Footer />
        </>
    )
}

export default Layout