const questions = [
  {
    questionText: "Logic-question1",
    answerOptions: [
      {
        answerText: "A",
        answerLink: "Logic-1-1",
        isCorrect: false,
      },
      { answerText: "B", answerLink: "Logic-1-2", isCorrect: false },
      { answerText: "C", answerLink: "Logic-1-3", isCorrect: true },
      { answerText: "D", answerLink: "Logic-1-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-1-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-1-6", isCorrect: false },
    ],
  },
  {
    questionText: "Logic-question2",
    answerOptions: [
      { answerText: "A", answerLink: "Logic-2-1", isCorrect: false },
      { answerText: "B", answerLink: "Logic-2-2", isCorrect: false },
      { answerText: "C", answerLink: "Logic-2-3", isCorrect: true },
      { answerText: "D", answerLink: "Logic-2-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-2-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-2-6", isCorrect: false },
    ],
  },
  {
    questionText: "Logic-question3",
    answerOptions: [
      { answerText: "A", answerLink: "Logic-3-1", isCorrect: false },
      { answerText: "B", answerLink: "Logic-3-2", isCorrect: true },
      { answerText: "C", answerLink: "Logic-3-3", isCorrect: false },
      { answerText: "D", answerLink: "Logic-3-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-3-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-3-6", isCorrect: false },
    ],
  },
  {
    questionText: "Logic-question4",
    answerOptions: [
      { answerText: "A", answerLink: "Logic-4-1", isCorrect: false },
      { answerText: "B", answerLink: "Logic-4-2", isCorrect: false },
      { answerText: "C", answerLink: "Logic-4-3", isCorrect: true },
      { answerText: "D", answerLink: "Logic-4-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-4-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-4-6", isCorrect: false },
    ],
  },
  {
    questionText: "Logic-question5",
    answerOptions: [
      { answerText: "A", answerLink: "Logic-5-1", isCorrect: false },
      { answerText: "B", answerLink: "Logic-5-2", isCorrect: false },
      { answerText: "C", answerLink: "Logic-5-3", isCorrect: false },
      { answerText: "D", answerLink: "Logic-5-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-5-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-5-6", isCorrect: true },
    ],
  },
  {
    questionText: "Logic-question6",
    answerOptions: [
      { answerText: "A", answerLink: "Logic-6-1", isCorrect: true },
      { answerText: "B", answerLink: "Logic-6-2", isCorrect: false },
      { answerText: "C", answerLink: "Logic-6-3", isCorrect: false },
      { answerText: "D", answerLink: "Logic-6-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-6-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-6-6", isCorrect: false },
    ],
  },
  {
    questionText: "Logic-question7",
    answerOptions: [
      { answerText: "A", answerLink: "Logic-7-1", isCorrect: false },
      { answerText: "B", answerLink: "Logic-7-2", isCorrect: true },
      { answerText: "C", answerLink: "Logic-7-3", isCorrect: false },
      { answerText: "D", answerLink: "Logic-7-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-7-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-7-6", isCorrect: false },
    ],
  },
  {
    questionText: "Logic-question8",
    answerOptions: [
      { answerText: "A", answerLink: "Logic-8-1", isCorrect: true },
      { answerText: "B", answerLink: "Logic-8-2", isCorrect: false },
      { answerText: "C", answerLink: "Logic-8-3", isCorrect: false },
      { answerText: "D", answerLink: "Logic-8-4", isCorrect: false },
      { answerText: "E", answerLink: "Logic-8-5", isCorrect: false },
      { answerText: "F", answerLink: "Logic-8-6", isCorrect: false },
    ],
  },
  {
    questionText: "Number-question1",
    answerOptions: [
      { answerText: "A", answerLink: "Number-1-1", isCorrect: false },
      { answerText: "B", answerLink: "Number-1-2", isCorrect: false },
      { answerText: "C", answerLink: "Number-1-3", isCorrect: false },
      { answerText: "D", answerLink: "Number-1-4", isCorrect: false },
      { answerText: "E", answerLink: "Number-1-5", isCorrect: false },
      { answerText: "F", answerLink: "Number-1-6", isCorrect: true },
    ],
  },
  {
    questionText: "Number-question2",
    answerOptions: [
      { answerText: "A", answerLink: "Number-2-1", isCorrect: false },
      { answerText: "B", answerLink: "Number-2-2", isCorrect: false },
      { answerText: "C", answerLink: "Number-2-3", isCorrect: false },
      { answerText: "D", answerLink: "Number-2-4", isCorrect: true },
      { answerText: "E", answerLink: "Number-2-5", isCorrect: false },
      { answerText: "F", answerLink: "Number-2-6", isCorrect: false },
    ],
  },
  {
    questionText: "Number-question3",
    answerOptions: [
      { answerText: "A", answerLink: "Number-3-1", isCorrect: true },
      { answerText: "B", answerLink: "Number-3-2", isCorrect: false },
      { answerText: "C", answerLink: "Number-3-3", isCorrect: false },
      { answerText: "D", answerLink: "Number-3-4", isCorrect: false },
      { answerText: "E", answerLink: "Number-3-5", isCorrect: false },
      { answerText: "F", answerLink: "Number-3-6", isCorrect: false },
    ],
  },
  {
    questionText: "Number-question4",
    answerOptions: [
      { answerText: "A", answerLink: "Number-4-1", isCorrect: false },
      { answerText: "B", answerLink: "Number-4-2", isCorrect: false },
      { answerText: "C", answerLink: "Number-4-3", isCorrect: false },
      { answerText: "D", answerLink: "Number-4-4", isCorrect: false },
      { answerText: "E", answerLink: "Number-4-5", isCorrect: true },
      { answerText: "F", answerLink: "Number-4-6", isCorrect: false },
    ],
  },
  {
    questionText: "Number-question5",
    answerOptions: [
      { answerText: "A", answerLink: "Number-5-1", isCorrect: false },
      { answerText: "B", answerLink: "Number-5-2", isCorrect: false },
      { answerText: "C", answerLink: "Number-5-3", isCorrect: true },
      { answerText: "D", answerLink: "Number-5-4", isCorrect: false },
      { answerText: "E", answerLink: "Number-5-5", isCorrect: false },
      { answerText: "F", answerLink: "Number-5-6", isCorrect: false },
    ],
  },
  {
    questionText: "Number-question6",
    answerOptions: [
      { answerText: "A", answerLink: "Number-6-1", isCorrect: true },
      { answerText: "B", answerLink: "Number-6-2", isCorrect: false },
      { answerText: "C", answerLink: "Number-6-3", isCorrect: false },
      { answerText: "D", answerLink: "Number-6-4", isCorrect: false },
      { answerText: "E", answerLink: "Number-6-5", isCorrect: false },
      { answerText: "F", answerLink: "Number-6-6", isCorrect: false },
    ],
  },
  {
    questionText: "Difference-question1",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-1-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-1-2", isCorrect: false },
      { answerText: "C", answerLink: "Difference-1-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-1-4", isCorrect: true },
      { answerText: "E", answerLink: "Difference-1-5", isCorrect: false },
      { answerText: "F", answerLink: "Difference-1-6", isCorrect: false },
    ],
  },
  {
    questionText: "Difference-question2",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-2-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-2-2", isCorrect: true },
      { answerText: "C", answerLink: "Difference-2-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-2-4", isCorrect: false },
      { answerText: "E", answerLink: "Difference-2-5", isCorrect: false },
      { answerText: "F", answerLink: "Difference-2-6", isCorrect: false },
    ],
  },
  {
    questionText: "Difference-question3",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-3-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-3-2", isCorrect: false },
      { answerText: "C", answerLink: "Difference-3-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-3-4", isCorrect: false },
      { answerText: "E", answerLink: "Difference-3-5", isCorrect: true },
      { answerText: "F", answerLink: "Difference-3-6", isCorrect: false },
    ],
  },
  {
    questionText: "Difference-question4",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-4-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-4-2", isCorrect: false },
      { answerText: "C", answerLink: "Difference-4-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-4-4", isCorrect: false },
      { answerText: "E", answerLink: "Difference-4-5", isCorrect: false },
      { answerText: "F", answerLink: "Difference-4-6", isCorrect: true },
    ],
  },
  {
    questionText: "Difference-question5",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-5-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-5-2", isCorrect: false },
      { answerText: "C", answerLink: "Difference-5-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-5-4", isCorrect: false },
      { answerText: "E", answerLink: "Difference-5-5", isCorrect: false },
      { answerText: "F", answerLink: "Difference-5-6", isCorrect: true },
    ],
  },
  {
    questionText: "Difference-question6",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-6-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-6-2", isCorrect: false },
      { answerText: "C", answerLink: "Difference-6-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-6-4", isCorrect: false },
      { answerText: "E", answerLink: "Difference-6-5", isCorrect: false },
      { answerText: "F", answerLink: "Difference-6-6", isCorrect: true },
    ],
  },
  {
    questionText: "Difference-question7",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-7-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-7-2", isCorrect: true },
      { answerText: "C", answerLink: "Difference-7-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-7-4", isCorrect: false },
      { answerText: "E", answerLink: "Difference-7-5", isCorrect: false },
      { answerText: "F", answerLink: "Difference-7-6", isCorrect: false },
    ],
  },
  {
    questionText: "Difference-question8",
    answerOptions: [
      { answerText: "A", answerLink: "Difference-8-1", isCorrect: false },
      { answerText: "B", answerLink: "Difference-8-2", isCorrect: false },
      { answerText: "C", answerLink: "Difference-8-3", isCorrect: false },
      { answerText: "D", answerLink: "Difference-8-4", isCorrect: true },
      { answerText: "E", answerLink: "Difference-8-5", isCorrect: false },
      { answerText: "F", answerLink: "Difference-8-6", isCorrect: false },
    ],
  },
  {
    questionText: "Matrix-question1",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-1-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-1-2", isCorrect: true },
      { answerText: "C", answerLink: "Matrix-1-3", isCorrect: false },
      { answerText: "D", answerLink: "Matrix-1-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-1-5", isCorrect: false },
      { answerText: "F", answerLink: "Matrix-1-6", isCorrect: false },
    ],
  },
  {
    questionText: "Matrix-question2",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-2-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-2-2", isCorrect: true },
      { answerText: "C", answerLink: "Matrix-2-3", isCorrect: false },
      { answerText: "D", answerLink: "Matrix-2-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-2-5", isCorrect: false },
      { answerText: "F", answerLink: "Matrix-2-6", isCorrect: false },
    ],
  },
  {
    questionText: "Matrix-question3",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-3-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-3-2", isCorrect: false },
      { answerText: "C", answerLink: "Matrix-3-3", isCorrect: false },
      { answerText: "D", answerLink: "Matrix-3-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-3-5", isCorrect: true },
      { answerText: "F", answerLink: "Matrix-3-6", isCorrect: false },
    ],
  },
  {
    questionText: "Matrix-question4",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-4-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-4-2", isCorrect: false },
      { answerText: "C", answerLink: "Matrix-4-3", isCorrect: false },
      { answerText: "D", answerLink: "Matrix-4-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-4-5", isCorrect: true },
      { answerText: "F", answerLink: "Matrix-4-6", isCorrect: false },
    ],
  },
  {
    questionText: "Matrix-question5",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-5-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-5-2", isCorrect: false },
      { answerText: "C", answerLink: "Matrix-5-3", isCorrect: false },
      { answerText: "D", answerLink: "Matrix-5-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-5-5", isCorrect: false },
      { answerText: "F", answerLink: "Matrix-5-6", isCorrect: true },
    ],
  },
  {
    questionText: "Matrix-question6",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-6-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-6-2", isCorrect: false },
      { answerText: "C", answerLink: "Matrix-6-3", isCorrect: true },
      { answerText: "D", answerLink: "Matrix-6-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-6-5", isCorrect: false },
      { answerText: "F", answerLink: "Matrix-6-6", isCorrect: false },
    ],
  },
  {
    questionText: "Matrix-question7",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-7-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-7-2", isCorrect: false },
      { answerText: "C", answerLink: "Matrix-7-3", isCorrect: false },
      { answerText: "D", answerLink: "Matrix-7-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-7-5", isCorrect: true },
      { answerText: "F", answerLink: "Matrix-7-6", isCorrect: false },
    ],
  },
  {
    questionText: "Matrix-question8",
    answerOptions: [
      { answerText: "A", answerLink: "Matrix-8-1", isCorrect: false },
      { answerText: "B", answerLink: "Matrix-8-2", isCorrect: false },
      { answerText: "C", answerLink: "Matrix-8-3", isCorrect: false },
      { answerText: "D", answerLink: "Matrix-8-4", isCorrect: false },
      { answerText: "E", answerLink: "Matrix-8-5", isCorrect: false },
      { answerText: "F", answerLink: "Matrix-8-6", isCorrect: true },
    ],
  },
];
export default questions;
